theme: jekyll-theme-slate
#highlighter: rogue
name: For Karma and Biryani Name
title: For Karma and Biryani

#url: "https://jeevankumarr.github.io"
#lsi: false
#exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
#permalink: pretty
#
## Build Settings
markdown: kramdown
#theme: minima


